### ISSUE TITLE
Error while running migrations for postgres

### ISSUE THREAD

**Issue by nileshtrivedi** [okupter/kitforstartups#4]
I was able to run `pnpm generate-migrations:postgres` but `pnpm migrate:postgres` gives this error:

```
> kitforstartups@0.0.1 migrate:postgres /Users/eshnil/code/kitforstartups
> tsx src/lib/drizzle/postgres/migrations/migrate.ts

file:///Users/eshnil/code/kitforstartups/node_modules/.pnpm/drizzle-orm@0.28.5_@libsql+client@0.3.2_@types+pg@8.10.2_mysql2@3.6.0_postgres@3.3.5/node_modules/drizzle-orm/migrator.mjs:21
        throw new Error(`Can't find meta/_journal.json file`);
              ^

Error: Can't find meta/_journal.json file
    at readMigrationFiles (/Users/eshnil/code/kitforstartups/node_modules/.pnpm/drizzle-orm@0.28.5_@libsql+client@0.3.2_@types+pg@8.10.2_mysql2@3.6.0_postgres@3.3.5/node_modules/src/migrator.ts:40:9)
    at migrate (/Users/eshnil/code/kitforstartups/node_modules/.pnpm/drizzle-orm@0.28.5_@libsql+client@0.3.2_@types+pg@8.10.2_mysql2@3.6.0_postgres@3.3.5/node_modules/src/postgres-js/migrator.ts:9:21)
    at <anonymous> (/Users/eshnil/code/kitforstartups/src/lib/drizzle/postgres/migrations/migrate.ts:19:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by nileshtrivedi** [comment]
Could be related to [this issue](https://github.com/drizzle-team/drizzle-orm/issues/680). Or might be possibly fixed in latest versions of drizzle-orm.

**Comment by JustinyAhin** [comment]
@nileshtrivedi thanks for raising this. I was passing the wrong folder in the migrate script.
This should be fixed by https://github.com/okupter/kitforstartups/commit/95c4374ed9b6f2406483236c363780ca2c59a0c8 now.

Feel free to reopen if it doesn't work for you.
